source "https://rubygems.org"

gem "pry"

gem "diamond", "~> 0.5", ">= 0.5.9"
gem "micromidi", "~> 0.2", ">= 0.2.0"
gem "midilib", "~> 2.0", ">= 2.0.4"
gem "midi-message", "~> 0.4", ">= 0.4.7"
gem "midi-nibbler", "~> 0.2", ">= 0.2.3"
gem "midi-topaz", "~> 0.2", ">= 0.2.5"
gem "patch", "~> 0.4", ">= 0.4.1"
gem "unimidi", "~> 0.4", ">= 0.4"
